export { default as mean } from "./mean/mean"
export { default as median } from "./median/median"
export { default as mode } from "./mode/mode"
export { default as sum } from "./sum/sum"
export { default as variance } from "./variance/variance"
export { default as std } from "./std/std"
export { q1, q2, q3, q4 } from "./quartile/quartile"
export { default as iqr } from "./iqr/iqr"
