export { nCr, nPr } from "./arrangements/arrangements"
export { default as binomial } from "./binomial/binomial"
export { default as clamp } from "./clamp/clamp"
export { default as factorial } from "./factorial/factorial"
export { default as gcd } from "./gcd/gcd"
export { default as hypergeometric } from "./hypergeometric/hypergeometric"
export { default as iqr } from "./iqr/iqr"
export { default as lcm } from "./lcm/lcm"
export { default as lerp } from "./lerp/lerp"
export { default as mean } from "./mean/mean"
export { default as median } from "./median/median"
export { default as mode } from "./mode/mode"
export { default as poisson } from "./poisson/poisson"
export { q1, q2, q3, q4 } from "./quartile/quartile"
export { default as randomInt } from "./random-int/random-int"
export { default as rotateMatrix } from "./rotate-matrix/rotate-matrix"
export { default as std } from "./std/std"
export { default as sum } from "./sum/sum"
export { default as variance } from "./variance/variance"
