export { default as binomial } from "./binomial/binomial"
export { default as factorial } from "./factorial/factorial"
export { default as iqr } from "./iqr/iqr"
export { default as mean } from "./mean/mean"
export { default as median } from "./median/median"
export { default as mode } from "./mode/mode"
export { nCr, nPr } from "./combinations/combinations"
export { q1, q2, q3, q4 } from "./quartile/quartile"
export { default as std } from "./std/std"
export { default as sum } from "./sum/sum"
export { default as variance } from "./variance/variance"
